### ISSUE TITLE
Using `azure_storage_account` returns error messages.

### ISSUE THREAD

**Issue by wallyhall** [puppetlabs/puppetlabs-azure_arm#10]
## What you expected to happen?

A storage account to be created.

## What happened?

Error message from `azure_storage_account.rb` line 219:

```
Alert: Exception during create.
The state of the resource is unknown.
ex is Invalid parameter id(:id) and backtrace is 
   [
       "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/errors.rb:157:in `fail'",
       "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:639:in `[]'",
       "/opt/puppetlabs/puppet/cache/lib/puppet/provider/azure_storage_account/azure_storage_account.rb:219:in `build_hash'",
       "/opt/puppetlabs/puppet/cache/lib/puppet/provider/azure_storage_account/azure_storage_account.rb:183:in `create'",
       "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/property/ensure.rb:16:in `block in defaultvalues'",
       "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/property.rb:491:in `set'",
```
... etc.

We have tried specifying `id` thusly too:

```
	azure_storage_account { "swtest-testy-mc-test" :
		  ensure    => present,
	  
		  id => "swtest-testy-mc-test",
	  
		  location => "uksouth",
		  resource_group => "UKS-NONPRD-DEVELOPMENT-RG6",
	}
```

but that returns an error too:

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: no parameter named 'id' (file: /etc/puppetlabs/code/environments/production/modules/azure_infrastructure/manifests/storageaccount.pp, line: 9) on Azure_storage_account[swtest-testy-mc-test] (file: /etc/puppetlabs/code/environments/production/modules/azure_infrastructure/manifests/storageaccount.pp, line: 9) on node ukwkpuppetent01.elevate-crp.co.uk
```

## How to reproduce it?

We're using the latest GA puppetlabs-azure_arm with the following manifest:

```
class azure_infrastructure::storageaccount::storageaccount_create {
	require azure_infrastructure::subscription::set_env
	azure_storage_account { "swtest-testy-mc-test" :
		  ensure    => present,
		  location => "uksouth",
		  resource_group => "UKS-NONPRD-DEVELOPMENT-RG6",
	}
```

## Versions:
```
[root@ukwkpuppetent01 ~]# puppet --version
5.5.1
[root@ukwkpuppetent01 ~]# facter os
{
  architecture => "x86_64",
  family => "RedHat",
  hardware => "x86_64",
  name => "CentOS",
  release => {
    full => "7.5.1804",
    major => "7",
    minor => "5"
  },
  selinux => {
    enabled => false
  }
}
[root@ukwkpuppetent01 ~]# puppet module list
/etc/puppetlabs/code/environments/production/modules
├── azure_infrastructure (???)
├── elevate (???)
├── iistest (???)
├── info (???)
├── liamjbennett-win_facts (v0.0.2)
├── linuxpackages (???)
├── motd (???)
├── profile (???)
├── puppet-download_file (v2.1.0)
├── puppet-windows_env (v2.3.0)
├── puppet-windows_firewall (v1.1.0)
├── puppet-windowsfeature (v2.1.0)
├── puppetlabs-acl (v1.1.2)
├── puppetlabs-azure (v1.1.1)
├── puppetlabs-azure_arm (v0.1.4)
├── puppetlabs-chocolatey (v2.0.2)
├── puppetlabs-dsc (v1.3.0)
├── puppetlabs-iis (v4.0.0)
├── puppetlabs-powershell (v2.1.0)
├── puppetlabs-reboot (v1.2.1)
├── puppetlabs-registry (v1.1.4)
├── puppetlabs-stdlib (v4.16.0)
├── puppetlabs-windows (v5.0.0)
├── puppetlabs-wsus_client (v1.0.3)
├── resolv (???)
├── sssd (???)
├── sudoers (???)
├── sunny (???)
├── vormetriclabs-set_env (v0.2.1)
├── windows_users (???)
├── windowspackages (???)
├── yumrepofiles (???)
└── zabbix (???)
/etc/puppetlabs/code/modules (no modules installed)
/opt/puppetlabs/puppet/modules
├── puppetlabs-facter_task (v0.3.0)
├── puppetlabs-package (v0.2.0)
├── puppetlabs-pe_accounts (v2016.5.0)
├── puppetlabs-pe_concat (v1.1.1)
├── puppetlabs-pe_hocon (v2016.2.0)
├── puppetlabs-pe_infrastructure (v2018.1.0)
├── puppetlabs-pe_inifile (v1.1.3)
├── puppetlabs-pe_install (v2018.1.0)
├── puppetlabs-pe_java_ks (v2016.4.0)
├── puppetlabs-pe_nginx (v2017.1.0)
├── puppetlabs-pe_postgresql (v2016.5.0)
├── puppetlabs-pe_puppet_authorization (v2016.2.0)
├── puppetlabs-pe_r10k (v2016.2.0)
├── puppetlabs-pe_razor (v0.2.1)
├── puppetlabs-pe_repo (v2018.1.0)
├── puppetlabs-pe_staging (v0.3.3)
├── puppetlabs-pe_support_script (v2.7.0)
├── puppetlabs-puppet_conf (v0.2.0)
├── puppetlabs-puppet_enterprise (v2018.1.0)
└── puppetlabs-service (v0.3.1)
[root@ukwkpuppetent01 ~]#
```

**Comment by gregohardy** [comment]
Hey @wallyhall. There isn't an id for storage account to name the resource. It's account_name. Here's a link to an example https://github.com/puppetlabs/puppetlabs-azure_arm/blob/aa9627951c048b4060b024a452386cc8ff045ecc/examples/create_vm.pp#L25

**Comment by wallyhall** [comment]
Thanks for the rapid response @gregohardy .

I had completely overlooked that example somehow!  I've changed our manifest thusly:

```
class azure_infrastructure::storageaccount::storageaccount_create {
    require azure_infrastructure::subscription::set_env
	
	azure_storage_account { 'swtest-testy-mc-test' :
		  ensure    => present,
		  parameters => {},
		  resource_group_name => 'UKS-NONPRD-DEVELOPMENT-RG6',
		  account_name => 'swtest-testy-mc-test',
		  location => "uksouth",
		  sku => {
			name => 'Standard_LRS',
			tier => 'Standard',
		  }
	}
}
```

(which as far as we can see, except for the string values, matches the provided example).

This throws a similar error when ran:

```
# puppet agent --test
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: no parameter named 'parameters' (file: /etc/puppetlabs/code/environments/production/modules/azure_infrastructure/manifests/storageaccount.pp, line: 9) on Azure_storage_account[swtest-testy-mc-test] (file: /etc/puppetlabs/code/environments/production/modules/azure_infrastructure/manifests/storageaccount.pp, line: 9) on node ukwkpuppetent01.elevate-crp.co.uk
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

We've tried eliminating `account_name`, `resource_group_name` and `parameters` respectively - and it it continues to error on the remaining properties (`Error 500 on SERVER: Server Error: no parameter named 'resource_group_name'` etc).

I apologise if we're missing the obvious - we've been staring at this for several days now and may be overlooking what's directly in front of us!

**Comment by gregohardy** [comment]
@wallyhall Could you run the agent with --debug --trace for me? Cheers!

**Comment by gregohardy** [comment]
You can DM me on Puppet's slack channel as well.

**Comment by gregohardy** [comment]
I think it might be azure rules for your storage account name? Storage account name must be between 3 and 24 characters in length and use numbers and lower-case letters only. I ran just your azure_storage_account call. This worked,

$base_name    = '1azureacceptance'
$rg               = "${base_name}-rg-name"
$storage_account  = "${base_name}sa"
$nsg              = "${base_name}-nsg"
$vnet             = "${base_name}-vnet"
$subnet           = "${base_name}-subnet"
$location         = 'uksouth'
$nic_base_name    = "${base_name}-nic"
$vm_base_name     = "${base_name}-vm"

	azure_storage_account { 'swtesttestymctest' :
		  ensure    => present,
		  parameters => {},
		  resource_group_name => $rg,
		  account_name => 'swtesttestymctest',
		  location => $location,
		  sku => {
			name => 'Standard_LRS',
			tier => 'Standard',
		  }
	}

**Comment by gregohardy** [comment]
@wallyhall I'm going to close this as it's not reflecting a problem in the module at the moment. Contact me personally for more help with your class definition ok?

**Comment by akkirao** [comment]
can you people add account kind and access tier for storage account in azure
