### ISSUE TITLE
Frequent ruby gems error .with azure_resource_group

### ISSUE THREAD

**Issue by akkirao** [puppetlabs/puppetlabs-azure_arm#13]
Alert: ex is Unable to get oauth2 token - response is #<Net::HTTPNotFound:0x0000558087428120> and body is  and backtrace is ["/etc/puppetlabs/code/environments/production/modules/azure_arm/lib/puppet/provider/azure_resource_group/azure_resource_group.rb:425:in `fetch_oauth2_token'", "/etc/puppetlabs/code/environments/production/modules/azure_arm/lib/puppet/provider/azure_resource_group/azure_resource_group.rb:399:in `authenticate'", "/etc/puppetlabs/code/environments/production/modules/azure_arm/lib/puppet/provider/azure_resource_group/azure_resource_group.rb:460:in `call_op'", "/etc/puppetlabs/code/environments/production/modules/azure_arm/lib/puppet/provider/azure_resource_group/azure_resource_group.rb:237:in `invoke_list_all'", "/etc/puppetlabs/code/environments/production/modules/azure_arm/lib/puppet/provider/azure_resource_group/azure_resource_group.rb:108:in `fetch_all'", "/etc/puppetlabs/code/environments/production/modules/azure_arm/lib/puppet/provider/azure_resource_group/azure_resource_group.rb:58:in `fetch_all_as_hash'", "/etc/puppetlabs/code/environments/production/modules/azure_arm/lib/puppet/provider/azure_resource_group/azure_resource_group.rb:46:in `instances'", "/etc/puppetlabs/code/environments/production/modules/azure_arm/lib/puppet/provider/azure_resource_group/azure_resource_group.rb:50:in `prefetch'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:357:in `prefetch'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:250:in `prefetch_if_necessary'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:109:in `block in evaluate'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/graph/relationship_graph.rb:119:in `traverse'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:171:in `evaluate'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:239:in `block (2 levels) in apply'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:519:in `block in thinmark'", "/opt/puppetlabs/puppet/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:518:in `thinmark'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:238:in `block in apply'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/log.rb:156:in `with_destination'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction/report.rb:146:in `as_logging_destination'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:237:in `apply'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:186:in `block (2 levels) in apply_catalog'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:519:in `block in thinmark'", "/opt/puppetlabs/puppet/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:518:in `thinmark'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:185:in `block in apply_catalog'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:232:in `block in benchmark'", "/opt/puppetlabs/puppet/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:231:in `benchmark'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:184:in `apply_catalog'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:369:in `run_internal'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:237:in `block in run'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:65:in `override'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:260:in `override'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:211:in `run'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/apply.rb:355:in `apply_catalog'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/apply.rb:280:in `block (2 levels) in main'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:65:in `override'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:260:in `override'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/apply.rb:280:in `block in main'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:65:in `override'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:260:in `override'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/apply.rb:233:in `main'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/apply.rb:174:in `run_command'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:375:in `block in run'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:667:in `exit_on_fail'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:375:in `run'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:136:in `run'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:73:in `execute'", "/usr/local/bin/puppet:5:in `<main>'"]
Error: Failed to apply catalog: Unable to get oauth2 token - response is #<Net::HTTPNotFound:0x0000558087428120> and body is

## Versions:

```
$ puppet apply <manifest in question> --debug --trace

$ puppet --version

$ facter os

$ puppet module list
```

## Logs:
```
Paste any relevant logs from a puppet run and syslog/messages
```

**Comment by akkirao** [comment]
caused due to environment variables
