### ISSUE TITLE
Module is hardcoded to use `ENV` variables?

### ISSUE THREAD

**Issue by wallyhall** [puppetlabs/puppetlabs-azure_arm#6]
## What you expected to happen?
Be able to configure the module via `azure.conf` as the documentation hints.

## What happened?
Configuration was not read.  Cannot even construct the `oauth` API call.  Looks like everything is hard coded against Ruby's `ENV` facade?

## How to reproduce it?
Try using the module via Puppet (rather than on the command line with `export`s set).

## Anything else we need to know?
Was pointed toward this as a solution by our account manager at PuppetLabs.

## Logs:
```
Alert: ex is Unable to get oauth2 token - response is #<Net::HTTPNotFound:0x00000000026ea698> and body is  and backtrace is ["/etc/puppetlabs/code/environments/production/modules/azure_arm/lib/puppet/provider/azure_sb_namespace/azure_sb_namespace.rb:462:in `fetch_oauth2_token'", "/etc/puppetlabs/code/environments/production/modules/azure_arm/lib/puppet/provider/azure_sb_namespace/azure_sb_namespace.rb:436:in `authenticate'", "/etc/puppetlabs/code/environments/production/modules/azure_arm/lib/puppet/provider/azure_sb_namespace/azure_sb_namespace.rb:213:in `invoke_list_all'", "/etc/puppetlabs/code/environments/production/modules/azure_arm/lib/puppet/provider/azure_sb_namespace/azure_sb_namespace.rb:95:in `fetch_all'", "/etc/puppetlabs/code/environments/production/modules/azure_arm/lib/puppet/provider/azure_sb_namespace/azure_sb_namespace.rb:63:in `fetch_all_as_hash'", "/etc/puppetlabs/code/environments/production/modules/azure_arm/lib/puppet/provider/azure_sb_namespace/azure_sb_namespace.rb:51:in `instances'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1164:in `block in instances'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1163:in `collect'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1163:in `instances'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/resource/ral.rb:24:in `search'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/indirection.rb:273:in `search'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/resource.rb:228:in `find_or_save_resources'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/resource.rb:142:in `block in main'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:65:in `override'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:260:in `override'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/resource.rb:137:in `main'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:383:in `run_command'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:375:in `block in run'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:661:in `exit_on_fail'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:375:in `run'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:137:in `run'", "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:73:in `execute'", "/opt/puppetlabs/puppet/bin/puppet:5:in `<main>'"]
Error: Could not run: Unable to get oauth2 token - response is #<Net::HTTPNotFound:0x00000000026ea698> and body is
```

**Comment by gregohardy** [comment]
Hi @wallyhall ! Thanks for the ticket. It appears that the readme, by mentioning the azure.conf, indicates that it is supported in the azure-arm module. The azure.conf file was plain text. You will need to specify the creds as ENV vars. There is an example in the readme under `Set environment variables`. Please note they are lower case.  A ticket is raised to support either upper or lower case keys for the creds.

**Comment by gregohardy** [comment]
If you have any further suggestions let us know. Cheers!

**Comment by EvilSmiff** [comment]
Is there any way we can support multiple subscriptions with this - due to the ENV vars?
